<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

	<!--Common definitions -->
	<xacro:include filename="$(find tom_description)/urdf/common.xacro"/>

	<!-- xacro macros Wheels-->
	<xacro:include filename="$(find tom_description)/urdf/wheels/wheels.urdf.xacro"/>

	<!-- xacro base (includes: base, Logos, Torso, wheels) -->
	<xacro:macro name="tom_base_v0" params="name">
		<!--virtual link used with gazebo physics engine-->
		<!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin,
         navigation stack dedpends on this frame -->
		<link name="${name}_footprint">
		  <visual>
		    <origin xyz="0 0 0" rpy="0 0 0" />
		    <geometry>
		      <box size="0.01 0.01 0.01" />
		    </geometry>
		    
		    <material name="White" />
		  </visual>
		  <collision>
		    <!-- -->
		    <origin xyz="0 0 0" rpy="0 0 0" />
		    <geometry>
		      <box size="0.001 0.001 0.001" />
		    </geometry>
		  </collision>
		</link>

		<joint name="${name}_footprint_joint" type="fixed">
		  <origin xyz="0 0 0.051" rpy="0 0 0" />
		  <child link="${name}_link" />
		  <parent link="${name}_footprint"/>
		</joint>

		<link name="${name}_link">
		 <visual>
		  <origin xyz="0 0 0" rpy="${90*DEG2RAD} 0 ${90*DEG2RAD}" />
		   <geometry>
		     <mesh filename="package://tom_description/meshes/base/item_profile.dae"/>       
		   </geometry>
		 </visual>
		  <collision>
		    <geometry>
		      <!--box size="${base_length + base_collision_offset} ${base_width + base_collision_offset} ${base_hight + base_collision_offset}"/-->
		      <mesh filename="package://tom_description/meshes/base/item_profile.dae"/>
		    </geometry>
		    <origin xyz="0 0 0" rpy="${90*DEG2RAD} 0 ${90*DEG2RAD}" />
		    <!--origin xyz="${-(base_length+base_collision_offset)/2.0+0.15} 0 ${-(base_hight + base_collision_offset)/2+0.1}" rpy="0 0 0"/-->
		  </collision>
		  <inertial>
		    <mass value="${base_frame_mass}"/>
		    <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
		  </inertial>
		</link>

		<link name="torso_link">
		 <visual>
		  <origin xyz="-0.01614 0 -0.76268" rpy="1.57 0 1.57" />
		   <geometry>
		     <mesh filename="package://tom_description/meshes/base/green_parts.dae"/>       
		   </geometry>
		 </visual>
		 <collision>
		    <geometry>
		      <!--box size="${torso_length + torso_collision_offset} ${torso_width + torso_collision_offset} ${torso_hight + torso_collision_offset}"/-->
					<mesh filename="package://tom_description/meshes/base/green_parts.dae"/> 
		    </geometry>
		    <origin xyz="-0.01614 0 -0.76268" rpy="1.57 0 1.57" />
		    <!--origin xyz="0.0 0 ${-(torso_hight + torso_collision_offset)/2+0.075}" rpy="0 0 0"/-->
		  </collision>
		  <inertial>
		    <mass value="10"/>
		    <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
		  </inertial>
		</link>

		<joint name="${name}_to_torso" type="fixed">
		  <parent link="${name}_link"/>
		  <child link="torso_link"/>
		  <origin xyz="0.01614 0 0.76268"/>
		</joint>

		<!-- Wheels-->
		<xacro:wheel parent="${name}_link" prefix="l_front_" reflect="1">
		  <origin xyz="0 0.303 -0.40" rpy="-1.57 0 0" />
		</xacro:wheel>

	 	<xacro:wheel parent="${name}_link" prefix="l_rear_" reflect="1">
		  <origin xyz="-0.8115 0.303 -0.40" rpy="-1.57 0 0" />
		</xacro:wheel>

		<xacro:wheel parent="${name}_link" prefix="r_front_" reflect="-1">
		  <origin xyz="0 -0.303 -0.40" rpy="-1.57 0 0" />
		</xacro:wheel>

		<xacro:wheel parent="${name}_link" prefix="r_rear_" reflect="-1">
		  <origin xyz="-0.8115 -0.303 -0.40" rpy="-1.57 0 0" />
		</xacro:wheel>

			<!-- Deco Logos-->
	  <link name="ICS_logo_blue_link">
		 <visual>
		  <origin xyz="0 0 0" rpy="1.57 0 1.57" />
		   <geometry>
		    <mesh filename="package://tom_description/meshes/base/logo_blue.dae"/>    
		   </geometry>
		 </visual>
		 <collision>
		  <origin xyz="0 0 0" rpy="1.57 0 1.57" />
		   <geometry>
		    <mesh filename="package://tom_description/meshes/base/logo_blue.dae"/>    
		   </geometry>
		 </collision>
		</link>

		<joint name="ICS_logo_blue" type="fixed">
		  <parent link="${name}_link"/>
		  <child link="ICS_logo_blue_link"/>
		  <origin xyz="0 0 0"/>
		</joint>

		<link name="ICS_logo_grey_link">
		 <visual>
		  <origin xyz="0 0 0" rpy="1.57 0 1.57" />
		   <geometry>
		    <mesh filename="package://tom_description/meshes/base/logo_grey.dae"/>    
		   </geometry>
		 </visual>
		 <collision>
		  <origin xyz="0 0 0" rpy="1.57 0 1.57" />
		   <geometry>
		    <mesh filename="package://tom_description/meshes/base/logo_grey.dae"/>    
		   </geometry>
		 </collision>
		</link>

		<joint name="ICS_logo_grey" type="fixed">
		  <parent link="${name}_link"/>
		  <child link="ICS_logo_grey_link"/>
		  <origin xyz="0 0 0"/>
		</joint>
	

  </xacro:macro>	

	


</robot>
