controller_list:
  - name: fake_right_arm_controller
    joints:
      - r_shoulder_pan_joint
      - r_shoulder_lift_joint
      - r_elbow_joint
      - r_wrist_1_joint
      - r_wrist_2_joint
      - r_wrist_3_joint
  - name: fake_left_arm_controller
    joints:
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_elbow_joint
      - l_wrist_1_joint
      - l_wrist_2_joint
      - l_wrist_3_joint
  - name: fake_base_group_controller
    joints:
      - l_front_wheel_joint
      - l_rear_wheel_joint
      - r_front_wheel_joint
      - r_rear_wheel_joint
  - name: fake_right_fingers_controller
    joints:
      - r_hand_joint_index_0
      - r_hand_joint_index_1
      - r_hand_joint_index_2
      - r_hand_joint_index_3
      - r_hand_joint_middle_0
      - r_hand_joint_middle_1
      - r_hand_joint_middle_2
      - r_hand_joint_middle_3
      - r_hand_joint_ring_0
      - r_hand_joint_ring_1
      - r_hand_joint_ring_2
      - r_hand_joint_ring_3
      - r_hand_joint_thumb_0
      - r_hand_joint_thumb_1
      - r_hand_joint_thumb_2
      - r_hand_joint_thumb_3
  - name: fake_left_fingers_controller
    joints:
      - l_hand_joint_index_0
      - l_hand_joint_index_1
      - l_hand_joint_index_2
      - l_hand_joint_index_3
      - l_hand_joint_middle_0
      - l_hand_joint_middle_1
      - l_hand_joint_middle_2
      - l_hand_joint_middle_3
      - l_hand_joint_ring_0
      - l_hand_joint_ring_1
      - l_hand_joint_ring_2
      - l_hand_joint_ring_3
      - l_hand_joint_thumb_0
      - l_hand_joint_thumb_1
      - l_hand_joint_thumb_2
      - l_hand_joint_thumb_3